name: Netlify Deploy

on:
  push:
    branches:
      - master # Trigger deployment on push to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js and install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify your Node.js version

      - name: Install dependencies using Yarn
        run: yarn install # Use Yarn to install dependencies

      - name: Build the project
        run: yarn build # This should match your package.json build script

      - name: Install Netlify CLI
        run: yarn global add netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          # Deploy the build directory (for React, it's usually 'build/')
          netlify deploy --dir=./dist --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
